server:
  port: 8088
logging:
  config: log4j2.yml
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/mt4_gold?useSSL=false&characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
juniter:
  email: juniterr@outlook.com